version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hub-controller"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-117ewo0q79bj8"
s3_prefix = "hub-controller"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
